version: 2

sources:
  - name: source_db
    description: 'Une BD source'
    database: source_db
    schema: RAW
    tables:
      - name: liste_agents
        description: 'Une liste des agents infiltres'
        columns:
          - name: agent_code
            tests:
                - unique
                - not_null

          - name: agent_name
            tests:
                - unique
                - not_null

          - name: working_area
            tests:
                - unique
                - not_null

          - name: commission
            tests:
                - unique
                - not_null

          - name: phone_no
            tests:
                - unique
                - not_null

          - name: country
            tests:
                - unique
                - not_null