version: 2

sources:
  - name: source_db
    description: 'Une BD source'
    database: source_db
    schema: RAW
    tables:
      - name: sample_table
        description: 'Une liste des agents infiltres'
        